language: java

sudo: false

script:
    - mvn clean
    
after_success:
  - cd ..
  - cat test.txt
  - git clone https://$GIT_USERNAME:$GIT_TOKEN@github.com/ConnectedHomes/hive-developer-portal.git
  - echo  $TRAVIS_BUILD_NUMBER > json-schemas-updated.txt
  - git add . json-schemas-updated.txt
  - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
  - git push origin master
