language: java

sudo: false

script:
    - mvn clean
    
after_success:
  - echo  $TRAVIS_BUILD_NUMBER > test.txt
  - git add . test.txt
  - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
  - git remote add origin-dev-portal https://$GIT_USERNAME:$GIT_TOKEN@github.com/ConnectedHomes/hive-developer-portal.git > /dev/null 2>&1
  - git push --quiet origin origin-dev-portal
